version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: .
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role == worker  # Constraint to run only on worker nodes
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/my_database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword
    ports:
      - "2137:8080"  # Map port 2137 on host to port 8080 on container
    networks:
      - backend

    

networks:
  backend:
    driver: overlay
    driver_opts:
      encrypted: "true

volumes:
  postgres-data:
    driver: local