apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.javaName }}
  labels:
    app: {{ .Values.javaName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.javaName }}
  template:
    metadata:
      labels:
        app: {{ .Values.javaName }}
    spec:
      containers:
        - name: {{ .Values.javaName }}
          image: szugop/example-java-api
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: POSTGRES_DB_URL
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgSecret }}
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: {{ .Values.javaName }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000